version: '3'
services:
 docker-app:
    image: projeto-app
    ports:
      - "8080:8080"
    depends_on:
      - docker-mongodb
    links:
      - docker-mongodb
 docker-mongodb:
    image: mongo
    container_name: "api-database"
    ports:
      - "27017:27017"